spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex?serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 4444
  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  #    database-platform: org.hibernate.dialect.MySQL8Dialect
  #    defer-datasource-initialization: false
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB
  devtools:
    livereload:
      enabled: true
  main:
    allow-bean-definition-overriding: true

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

#

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

#

server:
  port: 7061

#

org:
  zerock:
    upload:
      path: C:\\upload
itemImgLocation: C:/shop/item
#uploadPath: file:///C:/shop/

#