spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex?serverTimezone=UTC
    username: root
    password: 4444
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB
  devtools:
    livereload:
      enabled: true
  main:
    allow-bean-definition-overriding: true

#

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

#

server:
  port: 7061

#

org:
  zerock:
    upload:
      path: C:\\upload
itemImgLocation: C:/shop/item
#uploadPath: file:///C:/shop/

#