-- insert into blog_article(blog_title, blog_content, created_at, updated_at)
-- values ('제목 1', 'name 1', now(), now());
-- insert into blog_article(blog_title, blog_content, created_at, updated_at)
-- values ('제목 2', 'name 2', now(), now());
-- insert into blog_article(blog_title, blog_content, created_at, updated_at)
-- values ('제목 3', 'name 3', now(), now());
-- insert into blog_article(blog_title, blog_content, created_at, updated_at)
-- values ('제목 4', 'name 4', now(), now());
-- insert into blog_article(blog_title, blog_content, created_at, updated_at)
-- values ('제목 5', 'name 5', now(), now());
